name = "BEPS"
uuid = "28258c4d-138d-4793-867a-264e32c782b1"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MutableNamedTuples = "af6c499f-54b4-48cc-bbd2-094bba7533c7"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
DataFrames = "1.5, 1.6"
DelimitedFiles = "1.9"
LabelledArrays = "1.14"
MutableNamedTuples = "0.1.3"
Parameters = "0.12"
Reexport = "1"
UnPack = "1.0"
julia = "1.8, 1.9"
