name = "BEPS"
uuid = "28258c4d-138d-4793-867a-264e32c782b1"
version = "0.1.7"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HydroTools = "179359cd-bac3-4aa1-bccd-287172463ab0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[sources]
FieldMetadata = {url = "https://github.com/kongdd/FieldMetadata.jl"}
HydroTools = {url = "https://github.com/jl-pkgs/HydroTools.jl"}

[compat]
ComponentArrays = "0.15.29"
DataFrames = "1.5, 1.6, 1.7"
DelimitedFiles = "1.9"
DocStringExtensions = "0.9"
FieldMetadata = "0.3"
Functors = "0.5.2"
HydroTools = "0.1.7"
Parameters = "0.12"
Reexport = "1"
Statistics = "1.11.1"
UnPack = "1.0"
julia = "1.8, 1.9, 1.10"
